### ISSUE TITLE
Make this repository private?

### ISSUE THREAD

**Issue by johnousterhout** [willscott/pintos#1]
I'm a Professor at Stanford, and I'm teaching an Operating Systems course that uses Pintos for its class projects. I'm writing because I see that this repository is publicly accessible and appears to contain a complete set of solutions for the projects. This is a problem for us, because it makes it very easy for students to cheat. Even if they just look at your solution, and don't copy it, that will still reduce the educational experience for them. Would you be willing to take down this repository or at least make it private? If so, that would be a great help for us.

**Comment by willscott** [comment]
This repo was used by TAs to customize pintos for an OS class taught at the University of Washington. It does not have solutions. It also changes the system call interface to separate fork() and exec(), and correspondingly different homework assignments.

**Comment by johnousterhout** [comment]
Ahah, thanks for the clarification (there are so many Pintos repositories
on GitHub that I haven't been able to examine each of them in detail to see
exactly what they contain).

-John-
